import React, { createContext, useContext, useState } from 'react';

const TripContext = createContext();

export const useTrip = () => {
  const context = useContext(TripContext);
  if (context === undefined) {
    throw new Error('useTrip must be used within a TripProvider');
  }
  return context;
};

export const TripProvider = ({ children }) => {
  const [trips, setTrips] = useState([]);
  const [currentTrip, setCurrentTrip] = useState(null);

  const generateTrip = (destination, days, budget, travelers) => {
    const tripId = Date.now().toString();
    
    // Mock data - in real app, this would be generated by AI
    const mockHotels = [
      {
        id: '1',
        name: 'Grand Palace Hotel',
        location: `Downtown ${destination}`,
        price: budget === 'luxury' ? '$200-300/night' : budget === 'moderate' ? '$100-150/night' : '$50-80/night',
        rating: budget === 'luxury' ? 4.8 : budget === 'moderate' ? 4.2 : 3.8,
        image: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=400'
      },
      {
        id: '2',
        name: 'City Center Inn',
        location: `Central ${destination}`,
        price: budget === 'luxury' ? '$180-250/night' : budget === 'moderate' ? '$90-120/night' : '$40-70/night',
        rating: budget === 'luxury' ? 4.6 : budget === 'moderate' ? 4.0 : 3.6,
        image: 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=400'
      },
      {
        id: '3',
        name: 'Riverside Resort',
        location: `Riverside ${destination}`,
        price: budget === 'luxury' ? '$250-350/night' : budget === 'moderate' ? '$120-180/night' : '$60-100/night',
        rating: budget === 'luxury' ? 4.9 : budget === 'moderate' ? 4.4 : 4.0,
        image: 'https://images.pexels.com/photos/2373201/pexels-photo-2373201.jpeg?auto=compress&cs=tinysrgb&w=400'
      }
    ];

    const mockActivities = [
      {
        time: 'morning',
        title: `${destination} Historic Fort`,
        description: `Explore the majestic ${destination} Fort, a UNESCO World Heritage site.`,
        image: 'https://images.pexels.com/photos/1838640/pexels-photo-1838640.jpeg?auto=compress&cs=tinysrgb&w=400',
        price: 'Ticket: $15 per person'
      },
      {
        time: 'afternoon',
        title: 'Grand Mosque',
        description: `Visit the stunning Grand Mosque, one of the largest mosques in the region.`,
        image: 'https://images.pexels.com/photos/3737221/pexels-photo-3737221.jpeg?auto=compress&cs=tinysrgb&w=400',
        price: 'Ticket: Free'
      },
      {
        time: 'evening',
        title: 'Cultural Center',
        description: `Experience local culture and cuisine at the vibrant cultural center.`,
        image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=400',
        price: 'Entry: $10 per person'
      }
    ];

    const itinerary = Array.from({ length: days }, (_, index) => ({
      day: index + 1,
      activities: mockActivities
    }));

    const trip = {
      id: tripId,
      destination,
      days,
      budget,
      travelers,
      createdAt: new Date().toISOString(),
      hotels: mockHotels,
      itinerary
    };

    return trip;
  };

  const addTrip = (trip) => {
    setTrips(prev => [...prev, trip]);
    // In real app, this would be saved to backend
    const savedTrips = JSON.parse(localStorage.getItem('trips') || '[]');
    savedTrips.push(trip);
    localStorage.setItem('trips', JSON.stringify(savedTrips));
  };

  const value = {
    trips,
    currentTrip,
    addTrip,
    setCurrentTrip,
    generateTrip
  };

  return <TripContext.Provider value={value}>{children}</TripContext.Provider>;
};